server {
    listen 80;
    listen [::]:80;
    server_name pdv.temnaarea.site;

    root /var/www/temnaarea/pdv;
    index index.html;

    location /.well-known/acme-challenge/ {
        allow all;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    access_log /var/log/nginx/pdv.temnaarea.site.access.log;
    error_log /var/log/nginx/pdv.temnaarea.site.error.log;
}
